import { createContext, useContext, useState } from 'react';
import type { ReactNode } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Navbar & Global
    'nav.home': 'Accueil',
    'nav.features': 'Fonctionnalités',
    'nav.pricing': 'Tarifs',
    'nav.about': 'A propos',
    'nav.contact': 'Contact',
    'nav.tickets': 'Tickets',
    'nav.apidocs': 'API Docs',
    'nav.login': 'Connexion',
    'nav.register': 'Inscription',
    'nav.logout': 'Déconnexion',
    'nav.profile': 'Profil',
    'nav.settings': 'Paramètres',
    'nav.api': 'API',
    'nav.inbox': 'Boite de reception',
    'nav.apiAccess': 'Acces API',

    // Home Page
    'home.hero.title': 'Moteur de Recherche OSINT Avancé',
    'home.hero.subtitle': 'Trouvez des informations publiques sur le web en quelques secondes',
    'home.hero.description': 'Détectez les violations de données, les fuites et les menaces rapidement et en toute confidentialité. Dbs aide les individus et les organisations à protéger leurs informations.',
    'home.hero.badge': 'Plateforme de cybersécurité de confiance',
    'home.hero.button': 'Commencer la Recherche',
    'home.search.placeholder': 'Recherchez une adresse email, un domaine, une IP...',
    'home.search.button': 'Rechercher',
    'home.search.popular': 'Recherches populaires',
    'home.results.title': 'Résultats de Recherche',
    'home.results.databases': 'Base de données trouvées',
    'home.results.download': 'Télécharger les résultats',
    'home.results.noresults': 'Aucun résultat trouvé',
    'home.results.noresultstext': 'Aucune donnée n\'a été trouvée pour',
    'home.credits.title': 'Crédits Restants',
    'home.error.notloggedin': 'Veuillez vous connecter pour utiliser le moteur de recherche.',
    'home.error.beta_only': 'Les recherches sont actuellement réservées aux bêta testeurs.',
    'home.error.nocredits': 'Crédits insuffisants. Mettez à niveau votre plan.',
    'home.error.search': 'Erreur lors de la recherche. Veuillez réessayer.',
    'home.features.section': 'Fonctionnalités',
    'home.features.title': 'Outils puissants pour vos recherches',
    'home.features.subtitle': 'Des fonctionnalités avancées conçues pour les professionnels de la cybersécurité, les enquêteurs et les chercheurs.',
    'home.howitworks.section': 'Comment ça marche',
    'home.howitworks.title': 'Simple, rapide et sécurisé',
    'home.howitworks.subtitle': 'Trois étapes simples pour découvrir les informations dont vous avez besoin.',
    'home.howitworks.step1.title': 'Entrez votre recherche',
    'home.howitworks.step1.desc': 'Saisissez un email, nom d\'utilisateur, numéro de téléphone, adresse IP ou tout autre identifiant dans notre barre de recherche sécurisée.',
    'home.howitworks.step2.title': 'Analyse des sources',
    'home.howitworks.step2.desc': 'Dbs interroge plus de 15 sources de données en direct, incluant les bases de violations, les réseaux sociaux et les registres publics.',
    'home.howitworks.step3.title': 'Explorez les résultats',
    'home.howitworks.step3.desc': 'Visualisez les données dans un tableau de bord organisé, corrélez les informations, découvrez les connexions et exportez vos découvertes.',
    'home.trust.section': 'Confiance',
    'home.trust.title': 'Utilisé par des équipes de sécurité dans le monde entier',
    'home.trust.subtitle': 'Dbs est la plateforme de confiance des équipes de sécurité, des forces de l\'ordre et des entreprises dans plus de 50 pays. Nous offrons un support dédié, des intégrations personnalisées et des fonctionnalités de niveau entreprise.',
    'home.trust.gdpr': 'Conforme RGPD',
    'home.trust.audit': 'Audit trails',
    'home.trust.support': 'Support 24/7',
    'home.trust.sla': 'SLA garanti',
    'home.trust.orgs': 'Organisations',
    'home.trust.users': 'Utilisateurs actifs',
    'home.trust.searches': 'Recherches/mois',
    'home.trust.rating': 'Note moyenne',
    'home.trust.contact': 'Contacter l\'équipe commerciale',
    'home.cta.title': 'Prêt à sécuriser vos informations?',
    'home.cta.subtitle': 'Rejoignez des milliers de professionnels qui font confiance à Dbs pour leurs recherches OSINT et de cybersécurité.',
    'home.cta.button1': 'Commencer gratuitement',
    'home.cta.button2': 'Demander une démo',

    // Features Page
    'features.header.badge': 'Fonctionnalités',
    'features.header.title': 'Outils puissants pour l\'OSINT',
    'features.header.subtitle': 'Découvrez toutes les capacités de Dbs pour vos recherches et investigations.',
    'features.violations': 'Recherche de violations',
    'features.violations.desc': 'Accédez à une vaste base de données issue de fuites connues. Identifiez rapidement si vos informations personnelles ont été compromises.',
    'features.osint': 'OSINT avancé',
    'features.osint.desc': 'Analysez les réseaux sociaux, forums et sources publiques afin de reconstituer une identité numérique complète.',
    'features.darkweb': 'Dark Web Search',
    'features.darkweb.desc': 'Explorez le dark web en toute sécurité. Détectez les menaces potentielles et les données sensibles exposées.',
    'features.realtime': 'Résultats en temps réel',
    'features.realtime.desc': 'Profitez d’une infrastructure performante pour obtenir des résultats instantanés, sans délai.',
    'features.encryption': 'Chiffrement de bout en bout',
    'features.encryption.desc': 'Toutes vos recherches sont entièrement chiffrées. Vos données restent privées et ne sont jamais stockées.',
    'features.api': 'API REST',
    'features.api.desc': 'Intégrez facilement notre base de données dans vos outils et workflows. API complète avec documentation, exemples et support technique.',
    'features.section.types': 'Types de Recherche',
    'features.types.title': 'Recherchez par n\'importe quel identifiant',
    'features.types.desc': 'Dbs supporte une large gamme de types de recherche pour répondre à tous vos besoins.',
    'features.email': 'Email',
    'features.email.desc': 'Recherchez par adresse email pour trouver les violations, comptes associés et informations publiques.',
    'features.username': 'Nom d\'utilisateur',
    'features.username.desc': 'Trouvez tous les comptes et profils associés à un nom d\'utilisateur sur différentes plateformes.',
    'features.phone': 'Numéro de téléphone',
    'features.phone.desc': 'Identifiez les services et comptes liés à un numéro de téléphone, y compris les fuites de données.',
    'features.ip': 'Adresse IP',
    'features.ip.desc': 'Analysez une adresse IP pour obtenir la géolocalisation, l\'hébergeur et les informations de réputation.',
    'features.domain': 'Domaine',
    'features.domain.desc': 'Explorez les informations WHOIS, DNS, certificats SSL et historique d\'un nom de domaine.',
    'features.discord': 'Discord ID',
    'features.discord.desc': 'Recherchez par identifiant Discord pour trouver l\'activité et les serveurs associés.',
    'features.sources': 'Sources de données',
    'features.sources.title': '15+ sources interrogées en parallèle',
    'features.sources.desc': 'Nous agrégeons les données de multiples sources pour vous fournir les résultats les plus complets.',
    'features.breaches': 'Bases de violations',
    'features.breaches.count': '10B+ enregistrements',
    'features.social': 'Réseaux sociaux',
    'features.social.count': '20+ plateformes',
    'features.dark': 'Dark Web',
    'features.dark.count': 'Forums & marchés',
    'features.public': 'Registres publics',
    'features.public.count': 'WHOIS, DNS, etc.',
    'features.pastes': 'Pastes',
    'features.pastes.count': 'Pastebin & similaires',
    'features.security': 'Sécurité',
    'features.security.title': 'Votre confidentialité est notre priorité',
    'features.security.desc': 'Nous prenons la sécurité au sérieux. Toutes les données sont chiffrées en transit et au repos. Nous ne stockons pas vos recherches et nous respectons les réglementations de protection des données.',
    'features.aes256': 'Chiffrement AES-256',
    'features.gdpr': 'Conforme RGPD',
    'features.zerologo': 'Zero-log policy',
    'features.audit': 'Audit de sécurité',
    'features.encryption.type': 'Chiffrement',
    'features.cta.button': 'Commencer Maintenant',
    'features.cta.text': 'Prêt à explorer?',
    'features.cta.subtitle': 'Commencez gratuitement et découvrez la puissance de Dbs pour vos recherches OSINT.',

    // Pricing Page
    'pricing.header.badge': 'Tarifs',
    'pricing.header.title': 'Choisissez votre plan',
    'pricing.header.subtitle': 'Des options flexibles pour tous vos besoins de recherche OSINT.',
    'pricing.plan.free': 'Gratuit',
    'pricing.plan.beginner': 'Beginner',
    'pricing.plan.premium': 'Premium',
    'pricing.plan.pro': 'Pro',
    'pricing.price.beginner': '9.99',
    'pricing.price.pro': '24.99',
    'pricing.price.premium': '99',
    'pricing.price.period': '/lifetime',
    'pricing.price.crypto': 'Paiement unique en crypto',
    'pricing.price.advanced': 'Pour utilisateurs avancés',
    'pricing.price.ultimate': 'Accès ultime',
    'pricing.features': 'Caractéristiques',
    'pricing.button.buy': 'Acheter',
    'pricing.button.select': 'Choisir ce plan',
    'pricing.button.contact': 'Nous Contacter',
    'pricing.payment.title': 'Paiement en Litecoin (LTC)',
    'pricing.payment.desc': 'Tous les paiements sont effectués en Litecoin pour garantir votre anonymat et la sǸcuritǸ de vos transactions. Après achat, créez un ticket dans la catǸgorie "Accès Payant" pour activer votre plan.',
    'pricing.searches.per.day': 'recherches/jour',
    'pricing.feature.results': 'RǸsultats complets',
    'pricing.feature.support': 'Support 24h/24',
    'pricing.feature.osint': 'OSINT Search',
    'pricing.feature.api': 'API Access',
    'pricing.feature.intelx': 'IntelX',
    'pricing.faq.title': 'Questions Fréquemment Posées',
    'pricing.faq.q1': 'Puis-je annuler mon abonnement?',
    'pricing.faq.a1': 'Oui, vous pouvez annuler à tout moment.',
    'pricing.faq.payment.title': 'Comment fonctionne le paiement?',
    'pricing.faq.payment.desc': 'Cliquez sur "Acheter", creez un ticket dans la categorie "Acces Payant" en selectionnant votre plan. Nous vous enverrons une adresse LTC pour le paiement.',
    'pricing.faq.lifetime.title': 'Qu\'est-ce que "lifetime"?',
    'pricing.faq.lifetime.desc': 'Un paiement unique, acces a vie. Pas d\'abonnement mensuel, pas de frais caches. Vous payez une fois et profitez de votre plan pour toujours.',
    'pricing.faq.osint.title': 'Qu\'est-ce que l\'OSINT Search?',
    'pricing.faq.osint.desc': 'L\'OSINT Search donne acces a des bases de donnees avancees et des sources exclusives pour des recherches plus approfondies.',
    'pricing.faq.activation.title': 'Combien de temps pour activer mon plan?',
    'pricing.faq.activation.desc': 'Une fois le paiement confirme, votre plan est active en quelques minutes. Notre equipe est disponible 24h/24.',
    'pricing.cta.title': 'Prêt à passer au niveau supérieur?',
    'pricing.cta.subtitle': 'Débloquez tout le potentiel de Dbs avec un plan premium.',
    'pricing.cta.button.beginner': 'Commencer avec Beginner',
    'pricing.cta.button.entreprise': 'Choisir entreprise',

    // About Page
    'about.header.badge': 'À propos',
    'about.header.title': 'À propos de Dbs',
    'about.header.subtitle': 'Votre plateforme de confiance pour l\'OSINT.',
    'about.mission.title': 'Notre Mission',
    'about.mission.text': 'Fournir des outils OSINT puissants et accessibles à tous.',
    'about.values.title': 'Nos Valeurs',
    'about.values.subtitle': 'Ce qui nous guide',
    'about.team.title': 'Notre Équipe',
    'about.team.subtitle': 'Experts en cybersécurité et OSINT',
    'about.team.description': 'Les meilleures équipes derrière Dbs',
    'about.join.title': 'Rejoignez-Nous',
    'about.join.subtitle': 'Commencez votre voyage OSINT aujourd\'hui',
    'about.users': 'Utilisateurs Inscrits',

    // Contact Page
    'contact.header.badge': 'Contact',
    'contact.header.title': 'Nous Contacter',
    'contact.header.subtitle': 'Des questions? Nous sommes là pour vous aider.',
    'contact.notloggedin': 'Vous devez être connecté pour créer un ticket.',
    'contact.form.subject': 'Sujet',
    'contact.form.message': 'Message',
    'contact.form.category': 'Catégorie',
    'contact.form.category.contact': 'Contact',
    'contact.form.category.acces': 'Accès Payant',
    'contact.form.button': 'Envoyer',
    'contact.form.required': 'Veuillez remplir tous les champs.',
    'contact.form.selectplan': 'Veuillez sélectionner un plan.',
    'contact.form.success': 'Ticket créé avec succès!',
    'contact.form.error': 'Erreur lors de la création du ticket. Veuillez réessayer.',
    'contact.login.required': 'Vous devez être connecté pour envoyer un message.',
    'contact.faq.title': 'Questions Fréquemment Posées',

    // Tickets Page
    'tickets.header.badge': 'Support',
    'tickets.header.title': 'Mes Tickets',
    'tickets.header.subtitle': 'Gérez vos tickets de support',
    'tickets.header.owner': 'Gérez tous les tickets des utilisateurs',
    'tickets.header.user': 'Consultez vos tickets de support',
    'tickets.filter.all': 'Tous',
    'tickets.filter.open': 'Ouverts',
    'tickets.filter.closed': 'Fermés',
    'tickets.filter.deleteclosed': 'Supprimer tickets fermés',
    'tickets.filter.newticket': 'Nouveau ticket',
    'tickets.new': 'Nouveau Ticket',
    'tickets.open': 'Ouvert',
    'tickets.closed': 'Fermé',
    'tickets.status': 'Statut',
    'tickets.empty': 'Vous n\'avez pas encore créé de ticket.',
    'tickets.empty.title': 'Aucun ticket',
    'tickets.empty.all': 'Vous n\'avez pas encore créé de ticket.',
    'tickets.empty.open': 'Aucun ticket ouvert.',
    'tickets.empty.closed': 'Aucun ticket fermé.',
    'tickets.empty.button': 'Créer un ticket',
    'tickets.created': 'Créé le',
    'tickets.category': 'Catégorie',
    'tickets.subject': 'Sujet',
    'tickets.close': 'Fermer le ticket',
    'tickets.close.button': 'Fermer le ticket',
    'tickets.close.confirm': 'Êtes-vous sûr de vouloir fermer ce ticket?',
    'tickets.delete.button': 'Supprimer le message',
    'tickets.delete.confirm': 'Êtes-vous sûr de vouloir supprimer ce message?',
    'tickets.message.placeholder': 'Écrivez votre réponse...',
    'tickets.message.send': 'Envoyer',
    'tickets.message.upload': 'Télécharger une image',
    'tickets.message.sent': 'Message envoyé',
    'tickets.message.error': 'Erreur lors de l\'envoi du message',

    // API Docs Page
    'apidocs.header.badge': 'Documentation API',
    'apidocs.header.title': 'Documentation API Dbs',
    'apidocs.header.subtitle': 'Intégrez la puissance de Dbs dans votre application.',
    'apidocs.access.title': 'Accès Réservé',
    'apidocs.access.desc': 'Cette documentation est réservée aux utilisateurs Premium.',
    'apidocs.introduction': 'Introduction',
    'apidocs.authentication': 'Authentification',
    'apidocs.endpoints': 'Points de Terminaison',
    'apidocs.examples': 'Exemples',
    'apidocs.search': 'Recherche',
    'apidocs.credits': 'Crédits',
    'apidocs.apikey': 'Votre clé API',
    'apidocs.copy': 'Copier',
    'apidocs.copied': 'Copié!',

    // Footer
    'footer.brand.desc': 'Plateforme de cybersécurité offrant des capacités unifiées d\'OSINT et de recherche sur le dark web.',
    'footer.product': 'Produit',
    'footer.features': 'Fonctionnalités',
    'footer.pricing': 'Tarifs',
    'footer.api': 'API Documentation',
    'footer.changelog': 'Changelog',
    'footer.company': 'Entreprise',
    'footer.about': 'À propos',
    'footer.careers': 'Carrières',
    'footer.blog': 'Blog',
    'footer.support': 'Support',
    'footer.legal': 'Légal',
    'footer.privacy': 'Politique de confidentialité',
    'footer.terms': 'Conditions d\'utilisation',
    'footer.gdpr': 'RGPD',
    'footer.security': 'Sécurité',
    'footer.contact': 'Contact',
    'footer.discord': 'Discord',
    'footer.telegram': 'Telegram',
    'footer.copyright': 'Dbs #2026',
    'footer.secure': 'Sécurisé',
    'footer.gdpr_compliant': 'RGPD',
    'footer.rights': 'Tous droits réservés',

    // About Page - Additional
    'about.mission': 'Qui sommes-nous?',
    'about.mission.text1': 'Dbs est né de la conviction que les outils de cybersécurité ne devraient pas être réservés aux grandes entreprises. Notre équipe de passionnés en sécurité informatique a créé une plateforme accessible, puissante et respectueuse de la vie privée.',
    'about.mission.text2': 'Nous croyons que chaque individu et organisation devrait avoir accès aux outils nécessaires pour protéger ses informations numériques. C\'est pourquoi nous avons développé Dbs : une solution OSINT complète qui combine puissance et simplicité d\'utilisation.',
    'about.mission.text3': 'Basés en Europe, nous respectons les plus hauts standards de protection des données et nous engageons à une utilisation éthique de nos outils.',
    'about.year': 'Année de création',
    'about.countries': 'Pays',
    'about.members': 'Membres d\'équipe',
    'about.security': 'Sécurité d\'abord',
    'about.security.desc': 'La protection des données est au cœur de tout ce que nous faisons. Nous appliquons les meilleures pratiques de sécurité à chaque niveau.',
    'about.transparency': 'Transparence',
    'about.transparency.desc': 'Nous sommes ouverts sur nos pratiques, nos sources de données et la façon dont nous traitons les informations.',
    'about.ethics': 'Éthique',
    'about.ethics.desc': 'Nous nous engageons à une utilisation responsable de nos outils et refusons tout usage malveillant de notre plateforme.',
    'about.accessibility': 'Accessibilité',
    'about.accessibility.desc': 'Nous croyons que tout le monde devrait avoir accès à des outils de sécurité de qualité professionnelle.',
    'about.innovation': 'Innovation',
    'about.innovation.desc': 'Nous investissons continuellement dans la R&D pour rester à la pointe de la technologie OSINT.',
    'about.support': 'Support',
    'about.support.desc': 'Nous nous engageons à fournir un support exceptionnel à tous nos utilisateurs, quelle que soit leur taille.',

    // Contact Page - Additional
    'contact.login.title': 'Connexion requise',
    'contact.login.button': 'Se connecter',
    'contact.success.title': 'Ticket créé avec succès!',
    'contact.success.desc': 'Votre ticket a été créé. Vous pouvez suivre son état dans la section Tickets.',
    'contact.success.redirect': 'Redirection vers vos tickets...',
    'contact.form.plan.beginner': 'Beginner (3€)',
    'contact.form.plan.premium': 'Premium (99€)',
    'contact.form.message.template': 'Bonjour,\n\nJe souhaite acheter le plan {{plan}}.\n\nMerci de me fournir l\'adresse LTC pour le paiement.',
    'contact.faq.q1': 'Comment puis-je réinitialiser mon mot de passe?',
    'contact.faq.a1': 'Cliquez sur "Mot de passe oublié" sur la page de connexion. Vous recevrez un email avec un lien pour créer un nouveau mot de passe.',
    'contact.faq.q2': 'Quels types de recherches puis-je effectuer?',
    'contact.faq.a2': 'Dbs supporte les recherches par email, nom d\'utilisateur, numéro de téléphone, adresse IP, domaine, et identifiants de réseaux sociaux comme Discord.',
    'contact.faq.q3': 'Les résultats sont-ils confidentiels?',
    'contact.faq.a3': 'Oui, toutes vos recherches sont chiffrées et nous ne stockons pas l\'historique de vos requêtes. Votre confidentialité est notre priorité.',
    'contact.faq.q4': 'Comment fonctionne le paiement en LTC?',
    'contact.faq.a4': 'Une fois que vous créez un ticket dans la catégorie "Accès Payant", nous vous enverrons une adresse LTC. Après confirmation du paiement, votre plan sera activé immédiatement.',

    // Tickets Page - Additional
    'tickets.category.contact': 'Contact',
    'tickets.category.acces_payant': 'Accès Payant',
    'tickets.loading': 'Chargement...',
    'tickets.nologin': 'Vous devez être connecté pour voir vos tickets.',
    'tickets.owner.only': 'Seul le propriétaire peut effectuer cette action.',
    'tickets.grant.access': 'Accorder l\'accès',
    'tickets.reset.credits': 'Réinitialiser les crédits',
    'tickets.image.uploading': 'Téléchargement en cours...',
    'tickets.image.error': 'Erreur lors du téléchargement de l\'image.',
    'tickets.image.size': 'L\'image doit faire moins de 5MB.',

    // Login Page
    'login.title': 'Connexion',
    'login.subtitle': 'Entrez votre email pour recevoir un code de connexion',
    'login.email': 'Email',
    'login.button': 'Envoyer le code',
    'login.loading': 'Connexion en cours...',
    'login.success': 'Connexion réussie!',
    'login.error': 'Erreur de connexion',
    'login.otp.title': 'Entrez le code de vérification',
    'login.otp.code': 'Code de vérification',
    'login.otp.button': 'Vérifier',
    'login.otp.error': 'Code invalide',
    'login.noaccount': 'Vous n\'avez pas de compte?',
    'login.signup': 'Créer un compte ici',
    'login.email_label': 'Adresse email',
    'login.password': 'Mot de passe',
    'login.forgot_password': 'Mot de passe oublié',
    'login.send_code': 'Recevoir le code',
    'login.otp_sent': 'Un code a été envoyé à',
    'login.otp.sent': 'Code envoyé',
    'login.otp.subtitle': 'Entrez le code OTP',
    'login.change_email': 'Changer d\'email',

    // Register Page
    'register.title': 'Inscription',
    'register.subtitle': 'Créez votre compte Dbs',
    'register.email': 'Email',
    'register.email_label': 'Adresse email',
    'register.username': 'Nom d\'utilisateur',
    'register.password': 'Mot de passe',
    'register.confirmpass': 'Confirmer le mot de passe',
    'register.button': 'S\'inscrire',
    'register.loading': 'Création du compte...',
    'register.success': 'Compte créé avec succès!',
    'register.error': 'Erreur d\'inscription',
    'register.passwordmismatch': 'Les mots de passe ne correspondent pas',
    'register.hasaccount': 'Vous avez déjà un compte?',
    'register.login': 'Connectez-vous ici',
    'register.verification_sent': 'Email de vérification envoyé !',
    'register.verification_message': 'Un email de vérification vous a été envoyé à votre adresse mail.',
    'register.check_spam': '(Regardez dans les spams si vous ne trouvez pas l\'email)',
    'register.error.passwordmismatch': 'Les mots de passe ne correspondent pas',
    'register.error.passwordmin': 'Le mot de passe doit contenir au moins 8 caractères',
    'register.error.signup': 'Erreur lors de l\'inscription',

    // Home Page Errors
    'home.search.connection_error': 'Erreur de connexion. Veuillez réessayer.',
    'home.search.popular_tags': 'Recherches populaires',
    'home.search.email_tag': 'Email',
    'home.search.username_tag': 'Username',
    'home.search.discord_tag': 'Discord ID',
    'home.search.ip_tag': 'IP Address',
    'home.search.domain_tag': 'Domain',

    // Browser Notice
    'browser.notice.title': 'Recommandation',
    'browser.notice.subtitle': 'Optimisez votre expérience',
    'browser.notice.message': 'Pour une meilleure expérience et un fonctionnement optimal du site, nous vous recommandons d\'utiliser LibreWolf, un navigateur axé sur la confidentialité.',
    'browser.notice.button': 'Installer LibreWolf',
    'browser.notice.dismiss': 'Ne plus afficher ce message',

    // Privacy, GDPR, Terms, Security Pages
    'privacy.title': 'Politique de confidentialité',
    'privacy.badge': 'Légal',
    'privacy.updated': 'Dernière mise à jour: 1er janvier 2024',
    'privacy.intro': 'Chez Dbs, nous prenons la protection de vos données personnelles très au sérieux. Cette politique de confidentialité explique comment nous collectons, utilisons, stockons et protégeons vos informations lorsque vous utilisez notre plateforme.',
    'privacy.collected': 'Données collectées',
    'privacy.usage': 'Utilisation des données',
    'privacy.searches': 'Recherches et confidentialité',
    'privacy.sharing': 'Partage des données',
    'privacy.security': 'Sécurité des données',
    'gdpr.title': 'RGPD & protection des données',
    'gdpr.badge': 'Légal',
    'gdpr.updated': 'Dernière mise à jour: 1er janvier 2026',
    'gdpr.section1': '1. Objectif et champ d\'application',
    'gdpr.section1.desc': 'Cette page présente les principes RGPD appliqués par Dbs pour la collecte et le traitement des données personnelles liées à l\'utilisation de la plateforme (OSINT, détection de fuites et support).',
    'gdpr.section2': '2. Responsable du traitement',
    'gdpr.section2.desc': 'Dbs est responsable du traitement des données personnelles traitées dans le cadre du service.',
    'gdpr.section2.contact': 'Contact: privacy@Dbs.io',
    'gdpr.section2.dpo': 'DPO: dpo@Dbs.io',
    'gdpr.section3': '3. Bases légales du traitement',
    'gdpr.section3.contract': 'Exécution du contrat: création de compte, accès à la plateforme et facturation.',
    'gdpr.section3.consent': 'Consentement: cookies analytiques et communications non essentielles.',
    'gdpr.section3.legal': 'Obligation légale: conservation des données de facturation.',
    'gdpr.section3.legitimate': 'Intérêt légitime: sécurité, prévention des abus et amélioration du service.',
    'gdpr.section4': '4. Données traitées et minimisation',
    'gdpr.section4.desc': 'Nous collectons uniquement les données nécessaires à la fourniture du service et appliquons une politique de minimisation. Pour le détail des données et des cookies, consultez la Politique de confidentialité.',
    'gdpr.section5': '5. Finalités',
    'gdpr.section5.point1': 'Fournir, sécuriser et améliorer la plateforme.',
    'gdpr.section5.point2': 'Gérer les comptes, abonnements et paiements.',
    'gdpr.section5.point3': 'Assurer le support client et la réponse aux demandes.',
    'gdpr.section5.point4': 'Prévenir la fraude, l\'abus et les usages non autorisés.',
    'gdpr.section5.point5': 'Respecter les obligations légales et réglementaires.',
    'gdpr.section6': '6. Sous-traitants et transferts',
    'gdpr.section6.desc': 'Nous travaillons avec des sous-traitants techniques (hébergement, paiement, emails transactionnels) soumis à des clauses de confidentialité. Si un transfert hors EEE est nécessaire, nous mettons en place des garanties appropriées (ex: clauses contractuelles types).',
    'gdpr.section7': '7. Durée de conservation',
    'gdpr.section7.desc': 'Les données sont conservées pendant la durée du compte actif, puis archivées ou supprimées selon les délais légaux. Les détails figurent dans la Politique de confidentialité.',
    'gdpr.section8': '8. Vos droits',
    'gdpr.section8.point1': 'Droit d\'accès, de rectification et d\'effacement.',
    'gdpr.section8.point2': 'Droit à la limitation du traitement.',
    'gdpr.section8.point3': 'Droit d\'opposition au traitement.',
    'gdpr.section8.point4': 'Droit à la portabilité des données.',
    'gdpr.section9': '9. Exercer vos droits',
    'gdpr.section9.desc': 'Vous pouvez exercer vos droits à tout moment en écrivant à privacy@Dbs.io. Nous répondons dans un délai maximal de 30 jours, après vérification d\'identité si nécessaire.',
    'gdpr.section10': '10. Sécurité des données',
    'gdpr.section10.desc': 'Nous appliquons des mesures techniques et organisationnelles reconnues: chiffrement en transit et au repos, contrôles d\'accès, journalisation et audits réguliers.',
    'gdpr.section11': '11. Autorité de contrôle',
    'gdpr.section11.desc': 'Si vous estimez que vos droits ne sont pas respectés, vous pouvez contacter l\'autorité de contrôle compétente (CNIL: www.cnil.fr).',
    'terms.title': 'Conditions d\'utilisation',
    'terms.badge': 'Légal',
    'terms.updated': 'Dernière mise à jour: 1er janvier 2024',
    'terms.acceptance': 'En accédant et en utilisant Dbs, vous acceptez d\'être lié par ces conditions d\'utilisation. Si vous n\'acceptez pas ces conditions, veuillez ne pas utiliser notre service.',
    'terms.section1': '1. Acceptation des conditions',
    'terms.section2': '2. Description du service',
    'terms.section3': '3. Conditions d\'inscription',
    'terms.section4': '4. Utilisation acceptable',
    'terms.section5': '5. Utilisations interdites',
    'terms.section6': '6. Propriété intellectuelle',
    'terms.section7': '7. Limitation de responsabilité',
    'terms.section8': '8. Abonnements et paiements',
    'terms.section9': '9. Suspension et résiliation',
    'terms.section10': '10. Modifications des conditions',
    'terms.section11': '11. Droit applicable',
    'terms.section12': '12. Contact',
    'terms.service.desc': 'Dbs est une plateforme de cybersécurité offrant des services de recherche OSINT (Open Source Intelligence) et de surveillance du dark web. Nos services permettent aux utilisateurs de rechercher des informations publiquement disponibles et des données issues de fuites connues.',
    'terms.registration': 'Pour utiliser Dbs, vous devez:',
    'terms.reg1': 'Avoir au moins 18 ans',
    'terms.reg2': 'Fournir des informations exactes lors de l\'inscription',
    'terms.reg3': 'Maintenir la confidentialité de vos identifiants',
    'terms.reg4': 'Être responsable de toutes les activités sur votre compte',
    'terms.acceptable': 'Vous vous engagez à utiliser Dbs uniquement pour des fins légales et éthiques, notamment:',
    'terms.acceptable1': 'Vérifier vos propres données personnelles',
    'terms.acceptable2': 'Recherches de sécurité autorisées',
    'terms.acceptable3': 'Investigations légitimes dans le cadre professionnel',
    'terms.acceptable4': 'Protection contre les menaces de cybersécurité',
    'terms.prohibited': 'Il est strictement interdit d\'utiliser Dbs pour:',
    'terms.prohibited1': 'Harcèlement, traque ou intimidation de personnes',
    'terms.prohibited2': 'Activités frauduleuses ou illégales',
    'terms.prohibited3': 'Collecte de données pour spam ou marketing non sollicité',
    'terms.prohibited4': 'Tentative de nuire à des individus ou organisations',
    'terms.prohibited5': 'Revente ou redistribution des données obtenues',
    'terms.prohibited6': 'Automatisation abusive ou scraping massif',
    'terms.prohibited7': 'Contournement des limites de votre abonnement',
    'terms.ip.text': 'Tous les contenus, logos, designs et fonctionnalités de Dbs sont protégés par le droit de la propriété intellectuelle. Vous ne pouvez pas copier, modifier, distribuer ou exploiter commercialement notre plateforme sans autorisation écrite.',
    'terms.liability': 'Dbs est fourni "tel quel". Nous ne garantissons pas:',
    'terms.liability1': 'L\'exactitude ou l\'exhaustivité des résultats de recherche',
    'terms.liability2': 'La disponibilité continue du service',
    'terms.liability3': 'L\'absence de bugs ou d\'erreurs',
    'terms.liability.desc': 'Dbs ne pourra être tenu responsable des dommages directs ou indirects résultant de l\'utilisation de la plateforme.',
    'terms.subscription': 'Les abonnements sont facturés mensuellement ou annuellement selon votre choix. Les paiements sont non remboursables, sauf dans les cas prévus par la loi. Vous pouvez annuler votre abonnement à tout moment.',
    'terms.suspension': 'Nous nous réservons le droit de suspendre ou résilier votre compte en cas de:',
    'terms.suspension1': 'Violation de ces conditions d\'utilisation',
    'terms.suspension2': 'Utilisation abusive ou illégale de la plateforme',
    'terms.suspension3': 'Non-paiement des frais d\'abonnement',
    'terms.suspension4': 'Demande des autorités compétentes',
    'terms.modifications': 'Nous pouvons modifier ces conditions à tout moment. Les modifications importantes seront notifiées par email. Votre utilisation continue du service après modification constitue votre acceptation des nouvelles conditions.',
    'terms.law': 'Ces conditions sont régies par le droit français. Tout litige sera soumis à la juridiction des tribunaux de Paris, France.',
    'terms.contact': 'Pour toute question concernant ces conditions:',
    'terms.contact.email': 'Email: legal@Dbs.io',
    'terms.contact.address': 'Adresse: 123 Rue de la Sécurité, 75001 Paris, France',
    'terms.confirmation': 'En utilisant Dbs, vous confirmez avoir lu, compris et accepté ces conditions d\'utilisation.',
    'security.title': 'Sécurité et confiance',
    'security.badge': 'Légal',
    'security.updated': 'Dernière mise à jour: 1er janvier 2026',
    'security.section1': '1. Engagement sécurité',
    'security.section1.desc': 'La sécurité est au cœur de Dbs. Nous appliquons des pratiques reconnues pour protéger la confidentialité, l\'intégrité et la disponibilité des informations traitées par la plateforme.',
    'security.section2': '2. Protection des données',
    'security.section2.desc': 'Les données sont chiffrées en transit et au repos. Par défaut, Dbs ne conserve pas l\'historique de vos recherches, afin de limiter l\'exposition des informations sensibles.',
    'security.section3': '3. Contrôles d\'accès',
    'security.section3.point1': 'Authentification renforcée et options MFA.',
    'security.section3.point2': 'Principe du moindre privilège pour l\'accès interne.',
    'security.section3.point3': 'Revues d\'accès périodiques.',
    'security.section4': '4. Infrastructure et surveillance',
    'security.section4.desc': 'Notre infrastructure est durcie et surveillée en continu. Nous appliquons des mises à jour régulières, une segmentation des services et des alertes en cas d\'activité anormale.',
    'security.section5': '5. Développement sécurisé',
    'security.section5.desc': 'Le code est revu et testé avant chaque déploiement. Nous suivons les dépendances, appliquons des correctifs et réduisons les risques de régression sécurité.',
    'security.section6': '6. Gestion des incidents',
    'security.section6.desc': 'En cas d\'incident, nous appliquons un processus de réponse documenté, avec analyse, remédiation et communication appropriée si nécessaire.',
    'security.section7': '7. Divulgation responsable',
    'security.section7.desc': 'Vous pouvez signaler une vulnérabilité à security@Dbs.io. Nous analysons chaque signalement de bonne foi et communiquons sur la résolution.',
    'security.section8': '8. Bonnes pratiques utilisateur',
    'security.section8.point1': 'Utilisez un mot de passe unique et robuste.',
    'security.section8.point2': 'Activez la MFA dès que possible.',
    'security.section8.point3': 'Ne partagez pas vos identifiants.',
    'security.section8.point4': 'Vérifiez régulièrement l\'activité de votre compte.',
    'security.section9': '9. En savoir plus',
    'security.section9.desc': 'Pour les détails sur le traitement des données personnelles, consultez la Politique de confidentialité.',
  },
  en: {
    // Navbar & Global
    'nav.home': 'Home',
    'nav.features': 'Features',
    'nav.pricing': 'Pricing',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.tickets': 'Tickets',
    'nav.apidocs': 'API Docs',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.logout': 'Logout',
    'nav.profile': 'Profile',
    'nav.settings': 'Settings',
    'nav.api': 'API',
    'nav.inbox': 'Inbox',
    'nav.apiAccess': 'API Access',

    // Home Page
    'home.hero.title': 'Advanced OSINT Search Engine',
    'home.hero.subtitle': 'Find public information on the web in seconds',
    'home.hero.description': 'Detect data breaches, leaks and threats quickly and confidentially. Dbs helps individuals and organizations protect their information.',
    'home.hero.badge': 'Trusted Cybersecurity Platform',
    'home.hero.button': 'Start Searching',
    'home.search.placeholder': 'Search for an email, domain, IP...',
    'home.search.button': 'Search',
    'home.search.popular': 'Popular Searches',
    'home.results.title': 'Search Results',
    'home.results.databases': 'Databases found',
    'home.results.download': 'Download Results',
    'home.results.noresults': 'No results found',
    'home.results.noresultstext': 'No data was found for',
    'home.credits.title': 'Credits Remaining',
    'home.error.notloggedin': 'Please log in to use the search engine.',
    'home.error.beta_only': 'Searches are currently limited to beta testers.',
    'home.error.nocredits': 'Insufficient credits. Upgrade your plan.',
    'home.error.search': 'Error during search. Please try again.',
    'home.features.section': 'Features',
    'home.features.title': 'Powerful Tools for Your Research',
    'home.features.subtitle': 'Advanced features designed for cybersecurity professionals, investigators and researchers.',
    'home.howitworks.section': 'How It Works',
    'home.howitworks.title': 'Simple, Fast and Secure',
    'home.howitworks.subtitle': 'Three simple steps to discover the information you need.',
    'home.howitworks.step1.title': 'Enter Your Search',
    'home.howitworks.step1.desc': 'Enter an email, username, phone number, IP address or any other identifier in our secure search bar.',
    'home.howitworks.step2.title': 'Source Analysis',
    'home.howitworks.step2.desc': 'Dbs queries over 15 live data sources, including breach databases, social networks and public records.',
    'home.howitworks.step3.title': 'Explore Results',
    'home.howitworks.step3.desc': 'View data in an organized dashboard, correlate information, discover connections and export your findings.',
    'home.trust.section': 'Trust',
    'home.trust.title': 'Used by Security Teams Worldwide',
    'home.trust.subtitle': 'Dbs is the trusted platform for security teams, law enforcement and enterprises in over 50 countries. We offer dedicated support, custom integrations and enterprise-level features.',
    'home.trust.gdpr': 'GDPR Compliant',
    'home.trust.audit': 'Audit Trails',
    'home.trust.support': '24/7 Support',
    'home.trust.sla': 'Guaranteed SLA',
    'home.trust.orgs': 'Organizations',
    'home.trust.users': 'Active Users',
    'home.trust.searches': 'Searches/Month',
    'home.trust.rating': 'Average Rating',
    'home.trust.contact': 'Contact Sales Team',
    'home.cta.title': 'Ready to Secure Your Information?',
    'home.cta.subtitle': 'Join thousands of professionals who trust Dbs for their OSINT and cybersecurity research.',
    'home.cta.button1': 'Get Started Free',
    'home.cta.button2': 'Request a Demo',

    // Features Page
    'features.header.badge': 'Features',
    'features.header.title': 'Powerful Tools for OSINT',
    'features.header.subtitle': 'Discover all the capabilities of Dbs for your research and investigations.',
    'features.violations': 'Data Breach Search',
    'features.violations.desc': 'Access billions of records from known data breaches. Instantly detect if credentials have been compromised.',
    'features.osint': 'Advanced OSINT',
    'features.osint.desc': 'Search social networks, forums and public platforms for a complete view of a digital identity.',
    'features.darkweb': 'Dark Web Search',
    'features.darkweb.desc': 'Safely explore the dark web. Find information on potential threats and exposed data.',
    'features.realtime': 'Real-time Results',
    'features.realtime.desc': 'Our high-performance infrastructure provides instant results. No waiting, immediate answers.',
    'features.encryption': 'End-to-End Encryption',
    'features.encryption.desc': 'All your searches are encrypted. Your data remains private and secure. We don\'t store your queries.',
    'features.api': 'REST API',
    'features.api.desc': 'Integrate Dbs into your own tools and workflows. Documented API, code examples, and technical support.',
    'features.section.types': 'Search Types',
    'features.types.title': 'Search by any identifier',
    'features.types.desc': 'Dbs supports a wide range of search types to meet all your needs.',
    'features.email': 'Email',
    'features.email.desc': 'Search by email address to find breaches, associated accounts and public information.',
    'features.username': 'Username',
    'features.username.desc': 'Find all accounts and profiles associated with a username across different platforms.',
    'features.phone': 'Phone Number',
    'features.phone.desc': 'Identify services and accounts linked to a phone number, including data leaks.',
    'features.ip': 'IP Address',
    'features.ip.desc': 'Analyze an IP address to get geolocation, hosting provider and reputation information.',
    'features.domain': 'Domain',
    'features.domain.desc': 'Explore WHOIS information, DNS, SSL certificates and history of a domain name.',
    'features.discord': 'Discord ID',
    'features.discord.desc': 'Search by Discord ID to find associated activity and servers.',
    'features.sources': 'Data Sources',
    'features.sources.title': '15+ sources queried in parallel',
    'features.sources.desc': 'We aggregate data from multiple sources to provide you with the most complete results.',
    'features.breaches': 'Breach Databases',
    'features.breaches.count': '10B+ records',
    'features.social': 'Social Networks',
    'features.social.count': '20+ platforms',
    'features.dark': 'Dark Web',
    'features.dark.count': 'Forums & Markets',
    'features.public': 'Public Records',
    'features.public.count': 'WHOIS, DNS, etc.',
    'features.pastes': 'Pastes',
    'features.pastes.count': 'Pastebin & Similar',
    'features.security': 'Security',
    'features.security.title': 'Your privacy is our priority',
    'features.security.desc': 'We take security seriously. All data is encrypted in transit and at rest. We don\'t store your searches and we comply with data protection regulations.',
    'features.aes256': 'AES-256 Encryption',
    'features.gdpr': 'GDPR Compliant',
    'features.zerologo': 'Zero-log policy',
    'features.audit': 'Security Audit',
    'features.encryption.type': 'Encryption',
    'features.cta.button': 'Get Started',
    'features.cta.text': 'Ready to explore?',
    'features.cta.subtitle': 'Start for free and discover the power of Dbs for your OSINT research.',

    // Pricing Page
    'pricing.header.badge': 'Pricing',
    'pricing.header.title': 'Choose Your Plan',
    'pricing.header.subtitle': 'Flexible options for all your OSINT needs.',
    'pricing.plan.free': 'Free',
    'pricing.plan.beginner': 'Beginner',
    'pricing.plan.premium': 'Premium',
    'pricing.plan.pro': 'Pro',
    'pricing.price.beginner': '9.99',
    'pricing.price.pro': '24.99',
    'pricing.price.premium': '99.99',
    'pricing.price.period': '/lifetime',
    'pricing.price.crypto': 'Single payment in crypto',
    'pricing.price.advanced': 'For advanced users',
    'pricing.price.ultimate': 'Ultimate access',
    'pricing.features': 'Features',
    'pricing.button.buy': 'Buy',
    'pricing.button.select': 'Select This Plan',
    'pricing.button.contact': 'Contact Us',
    'pricing.payment.title': 'Payment in Litecoin (LTC)',
    'pricing.payment.desc': 'All payments are made in Litecoin to guarantee your anonymity and transaction security. After purchase, create a ticket in the "Paid Access" category to activate your plan.',
    'pricing.searches.per.day': 'searches/day',
    'pricing.feature.results': 'Complete Results',
    'pricing.feature.support': '24/7 Support',
    'pricing.feature.osint': 'OSINT Search',
    'pricing.feature.api': 'API Access',
    'pricing.feature.intelx': 'IntelX',
    'pricing.faq.title': 'Frequently Asked Questions',
    'pricing.faq.q1': 'Can I cancel my subscription?',
    'pricing.faq.a1': 'Yes, you can cancel at any time.',
    'pricing.faq.payment.title': 'How does payment work?',
    'pricing.faq.payment.desc': 'Click "Buy", create a ticket in the "Paid Access" category and select your plan. We will send you an LTC address for payment.',
    'pricing.faq.lifetime.title': 'What is "lifetime"?',
    'pricing.faq.lifetime.desc': 'A single payment, lifetime access. No monthly subscription, no hidden fees. You pay once and keep your plan forever.',
    'pricing.faq.osint.title': 'What is OSINT Search?',
    'pricing.faq.osint.desc': 'OSINT Search gives access to advanced databases and exclusive sources for deeper searches.',
    'pricing.faq.activation.title': 'How long to activate my plan?',
    'pricing.faq.activation.desc': 'Once payment is confirmed, your plan is activated within minutes. Our team is available 24/7.',
    'pricing.cta.title': 'Ready to Level Up?',
    'pricing.cta.subtitle': 'Unlock the full potential of Dbs with a premium plan.',
    'pricing.cta.button.beginner': 'Start with Beginner',
    'pricing.cta.button.premium': 'Choose Premium',

    // About Page
    'about.header.badge': 'About',
    'about.header.title': 'About Dbs',
    'about.header.subtitle': 'Your trusted platform for OSINT.',
    'about.mission.title': 'Our Mission',
    'about.mission.text': 'To provide powerful and accessible OSINT tools to everyone.',
    'about.values.title': 'Our Values',
    'about.values.subtitle': 'What Guides Us',
    'about.team.title': 'Our Team',
    'about.team.subtitle': 'Cybersecurity and OSINT Experts',
    'about.team.description': 'The best teams behind Dbs',
    'about.join.title': 'Join Us',
    'about.join.subtitle': 'Start your OSINT journey today',
    'about.users': 'Registered Users',

    // Contact Page
    'contact.header.badge': 'Contact',
    'contact.header.title': 'Contact Us',
    'contact.header.subtitle': 'Have questions? We are here to help.',
    'contact.notloggedin': 'You must be logged in to create a ticket.',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.category': 'Category',
    'contact.form.category.contact': 'Contact',
    'contact.form.category.acces': 'Paid Access',
    'contact.form.button': 'Send',
    'contact.form.required': 'Please fill in all fields.',
    'contact.form.selectplan': 'Please select a plan.',
    'contact.form.success': 'Ticket created successfully!',
    'contact.form.error': 'Error creating ticket. Please try again.',
    'contact.login.required': 'You must be logged in to send a message.',
    'contact.faq.title': 'Frequently Asked Questions',

    // Tickets Page
    'tickets.header.badge': 'Support',
    'tickets.header.title': 'My Tickets',
    'tickets.header.subtitle': 'Manage your support tickets.',
    'tickets.header.owner': 'Manage all user tickets',
    'tickets.header.user': 'View your support tickets',
    'tickets.filter.all': 'All',
    'tickets.filter.open': 'Open',
    'tickets.filter.closed': 'Closed',
    'tickets.filter.deleteclosed': 'Delete closed tickets',
    'tickets.filter.newticket': 'New Ticket',
    'tickets.new': 'New Ticket',
    'tickets.open': 'Open',
    'tickets.closed': 'Closed',
    'tickets.status': 'Status',
    'tickets.empty': 'You haven\'t created any tickets yet.',
    'tickets.empty.title': 'No Tickets',
    'tickets.empty.all': 'You haven\'t created any tickets yet.',
    'tickets.empty.open': 'No open tickets.',
    'tickets.empty.closed': 'No closed tickets.',
    'tickets.empty.button': 'Create Ticket',
    'tickets.created': 'Created on',
    'tickets.category': 'Category',
    'tickets.subject': 'Subject',
    'tickets.close': 'Close Ticket',
    'tickets.close.button': 'Close Ticket',
    'tickets.close.confirm': 'Are you sure you want to close this ticket?',
    'tickets.delete.button': 'Delete Message',
    'tickets.delete.confirm': 'Are you sure you want to delete this message?',
    'tickets.confirm.close': 'Are you sure you want to close this ticket?',
    'tickets.message.placeholder': 'Write your reply...',
    'tickets.message.send': 'Send',
    'tickets.message.upload': 'Upload Image',
    'tickets.message.sent': 'Message sent',
    'tickets.message.error': 'Error sending message',

    // API Docs Page
    'apidocs.header.badge': 'API Documentation',
    'apidocs.header.title': 'Dbs API Documentation',
    'apidocs.header.subtitle': 'Integrate the power of Dbs into your application.',
    'apidocs.access.title': 'Restricted Access',
    'apidocs.access.desc': 'This documentation is reserved for Premium users.',
    'apidocs.introduction': 'Introduction',
    'apidocs.authentication': 'Authentication',
    'apidocs.endpoints': 'Endpoints',
    'apidocs.examples': 'Examples',
    'apidocs.search': 'Search',
    'apidocs.credits': 'Credits',
    'apidocs.apikey': 'Your API Key',
    'apidocs.copy': 'Copy',
    'apidocs.copied': 'Copied!',

    // Footer
    'footer.brand.desc': 'Cybersecurity platform offering unified OSINT and dark web search capabilities.',
    'footer.product': 'Product',
    'footer.features': 'Features',
    'footer.pricing': 'Pricing',
    'footer.api': 'API Documentation',
    'footer.changelog': 'Changelog',
    'footer.company': 'Company',
    'footer.about': 'About',
    'footer.careers': 'Careers',
    'footer.blog': 'Blog',
    'footer.support': 'Support',
    'footer.legal': 'Legal',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.gdpr': 'GDPR',
    'footer.security': 'Security',
    'footer.contact': 'Contact',
    'footer.discord': 'Discord',
    'footer.telegram': 'Telegram',
    'footer.copyright': 'Dbs #2025',
    'footer.secure': 'Secure',
    'footer.gdpr_compliant': 'GDPR',
    'footer.rights': 'All rights reserved',

    // About Page - Additional
    'about.mission': 'Who We Are?',
    'about.mission.text1': 'Dbs was born from the conviction that cybersecurity tools should not be reserved for large enterprises. Our team of passionate information security experts created an accessible, powerful and privacy-respecting platform.',
    'about.mission.text2': 'We believe that every individual and organization should have access to the tools they need to protect their digital information. That\'s why we developed Dbs: a complete OSINT solution that combines power with ease of use.',
    'about.mission.text3': 'Based in Europe, we respect the highest standards of data protection and are committed to ethical use of our tools.',
    'about.year': 'Year Founded',
    'about.countries': 'Countries',
    'about.members': 'Team Members',
    'about.security': 'Security First',
    'about.security.desc': 'Data protection is at the heart of everything we do. We apply the best security practices at every level.',
    'about.transparency': 'Transparency',
    'about.transparency.desc': 'We are open about our practices, our data sources and how we handle information.',
    'about.ethics': 'Ethics',
    'about.ethics.desc': 'We are committed to responsible use of our tools and refuse any malicious use of our platform.',
    'about.accessibility': 'Accessibility',
    'about.accessibility.desc': 'We believe everyone should have access to professional-quality security tools.',
    'about.innovation': 'Innovation',
    'about.innovation.desc': 'We continuously invest in R&D to stay at the forefront of OSINT technology.',
    'about.support': 'Support',
    'about.support.desc': 'We are committed to providing exceptional support to all our users, regardless of their size.',

    // Contact Page - Additional
    'contact.login.title': 'Login Required',
    'contact.login.button': 'Login',
    'contact.success.title': 'Ticket Created Successfully!',
    'contact.success.desc': 'Your ticket has been created. You can track its status in the Tickets section.',
    'contact.success.redirect': 'Redirecting to your tickets...',
    'contact.form.plan.beginner': 'Beginner ($3)',
    'contact.form.plan.premium': 'Premium ($7)',
    'contact.form.message.template': 'Hello,\n\nI would like to purchase the {{plan}} plan.\n\nPlease provide me with the LTC address for payment.',
    'contact.faq.q1': 'How can I reset my password?',
    'contact.faq.a1': 'Click "Forgot Password" on the login page. You will receive an email with a link to create a new password.',
    'contact.faq.q2': 'What types of searches can I perform?',
    'contact.faq.a2': 'Dbs supports searches by email, username, phone number, IP address, domain, and social media identifiers like Discord.',
    'contact.faq.q3': 'Are the results confidential?',
    'contact.faq.a3': 'Yes, all your searches are encrypted and we don\'t store your query history. Your privacy is our priority.',
    'contact.faq.q4': 'How does LTC payment work?',
    'contact.faq.a4': 'Once you create a ticket in the "Paid Access" category, we will send you an LTC address. After payment confirmation, your plan will be activated immediately.',

    // Tickets Page - Additional
    'tickets.category.contact': 'Contact',
    'tickets.category.acces_payant': 'Paid Access',
    'tickets.loading': 'Loading...',
    'tickets.nologin': 'You must be logged in to view your tickets.',
    'tickets.owner.only': 'Only the owner can perform this action.',
    'tickets.grant.access': 'Grant Access',
    'tickets.reset.credits': 'Reset Credits',
    'tickets.image.uploading': 'Uploading...',
    'tickets.image.error': 'Error uploading image.',
    'tickets.image.size': 'Image must be less than 5MB.',

    // Login Page
    'login.title': 'Login',
    'login.subtitle': 'Access your Dbs account',
    'login.email': 'Email Address',
    'login.password': 'Password',
    'login.remember': 'Remember me',
    'login.button': 'Log In',
    'login.loading': 'Logging in...',
    'login.success': 'Login successful!',
    'login.error': 'Login error',
    'login.forgot': 'Forgot password?',
    'login.otp.title': 'Enter Verification Code',
    'login.otp.subtitle': 'Enter your email to receive a login code',
    'login.otp.code': 'Verification Code',
    'login.otp.button': 'Verify',
    'login.otp.error': 'Invalid or expired code',
    'login.otp.sent': 'OTP Code sent! Check your inbox (and spam folder).',
    'login.noaccount': 'Don\'t have an account?',
    'login.signup': 'Sign up here',
    'login.email_label': 'Email Address',
    'login.forgot_password': 'Forgot Password',
    'login.send_code': 'Send Code',
    'login.otp_sent': 'A code has been sent to',
    'login.change_email': 'Change Email',

    // Register Page
    'register.title': 'Register',
    'register.subtitle': 'Create your Dbs account',
    'register.email': 'Email',
    'register.email_label': 'Email Address',
    'register.username': 'Username',
    'register.password': 'Password',
    'register.confirmpass': 'Confirm Password',
    'register.button': 'Register',
    'register.loading': 'Creating account...',
    'register.success': 'Account created successfully!',
    'register.error': 'Registration error',
    'register.passwordmismatch': 'Passwords do not match',
    'register.hasaccount': 'Already have an account?',
    'register.login': 'Log in here',
    'register.verification_sent': 'Verification Email Sent!',
    'register.verification_message': 'A verification email has been sent to your email address.',
    'register.check_spam': '(Check your spam folder if you don\'t see the email)',
    'register.error.passwordmismatch': 'Passwords do not match',
    'register.error.passwordmin': 'Password must be at least 8 characters long',
    'register.error.signup': 'Error during registration',

    // Home Page Errors
    'home.search.connection_error': 'Connection error. Please try again.',
    'home.search.popular_tags': 'Popular Searches',
    'home.search.email_tag': 'Email',
    'home.search.username_tag': 'Username',
    'home.search.discord_tag': 'Discord ID',
    'home.search.ip_tag': 'IP Address',
    'home.search.domain_tag': 'Domain',

    // Browser Notice
    'browser.notice.title': 'Recommendation',
    'browser.notice.subtitle': 'Optimize your experience',
    'browser.notice.message': 'For a better experience and optimal site performance, we recommend using LibreWolf, a privacy-focused browser.',
    'browser.notice.button': 'Install LibreWolf',
    'browser.notice.dismiss': 'Don\'t show this message again',

    // Privacy, GDPR, Terms, Security Pages
    'privacy.title': 'Privacy Policy',
    'privacy.badge': 'Legal',
    'privacy.updated': 'Last updated: January 1, 2024',
    'privacy.intro': 'At Dbs, we take the protection of your personal data very seriously. This privacy policy explains how we collect, use, store and protect your information when you use our platform.',
    'privacy.collected': 'Data Collected',
    'privacy.usage': 'Data Usage',
    'privacy.searches': 'Searches and Privacy',
    'privacy.sharing': 'Data Sharing',
    'privacy.security': 'Data Security',
    'gdpr.title': 'GDPR & Data Protection',
    'gdpr.badge': 'Legal',
    'gdpr.updated': 'Last updated: January 1, 2026',
    'gdpr.section1': '1. Objective and Scope',
    'gdpr.section1.desc': 'This page presents the GDPR principles applied by Dbs for the collection and processing of personal data related to the use of the platform (OSINT, breach detection and support).',
    'gdpr.section2': '2. Data Controller',
    'gdpr.section2.desc': 'Dbs is responsible for the processing of personal data processed in the context of the service.',
    'gdpr.section2.contact': 'Contact: privacy@Dbs.io',
    'gdpr.section2.dpo': 'DPO: dpo@Dbs.io',
    'gdpr.section3': '3. Legal Bases for Processing',
    'gdpr.section3.contract': 'Contract Execution: account creation, platform access and billing.',
    'gdpr.section3.consent': 'Consent: analytical cookies and non-essential communications.',
    'gdpr.section3.legal': 'Legal Obligation: retention of billing data.',
    'gdpr.section3.legitimate': 'Legitimate Interest: security, abuse prevention and service improvement.',
    'gdpr.section4': '4. Data Processed and Minimization',
    'gdpr.section4.desc': 'We collect only the data necessary to provide the service and apply a minimization policy. For details on data and cookies, see the Privacy Policy.',
    'gdpr.section5': '5. Purposes',
    'gdpr.section5.point1': 'Provide, secure and improve the platform.',
    'gdpr.section5.point2': 'Manage accounts, subscriptions and payments.',
    'gdpr.section5.point3': 'Ensure customer support and response to requests.',
    'gdpr.section5.point4': 'Prevent fraud, abuse and unauthorized uses.',
    'gdpr.section5.point5': 'Comply with legal and regulatory obligations.',
    'gdpr.section6': '6. Subprocessors and Transfers',
    'gdpr.section6.desc': 'We work with technical subprocessors (hosting, payment, transactional emails) bound by confidentiality clauses. If a transfer outside the EEA is necessary, we implement appropriate safeguards (e.g., standard contractual clauses).',
    'gdpr.section7': '7. Retention Period',
    'gdpr.section7.desc': 'Data is retained for the duration of the active account, then archived or deleted according to legal deadlines. Details are in the Privacy Policy.',
    'gdpr.section8': '8. Your Rights',
    'gdpr.section8.point1': 'Right of access, rectification and erasure.',
    'gdpr.section8.point2': 'Right to restrict processing.',
    'gdpr.section8.point3': 'Right to object to processing.',
    'gdpr.section8.point4': 'Right to data portability.',
    'gdpr.section9': '9. Exercising Your Rights',
    'gdpr.section9.desc': 'You can exercise your rights at any time by writing to privacy@Dbs.io. We respond within a maximum of 30 days, after identity verification if necessary.',
    'gdpr.section10': '10. Data Security',
    'gdpr.section10.desc': 'We apply recognized technical and organizational measures: encryption in transit and at rest, access controls, logging and regular audits.',
    'gdpr.section11': '11. Supervisory Authority',
    'gdpr.section11.desc': 'If you believe your rights are not respected, you can contact the competent supervisory authority (CNIL: www.cnil.fr).',
    'terms.title': 'Terms of Service',
    'terms.badge': 'Legal',
    'terms.updated': 'Last updated: January 1, 2024',
    'terms.acceptance': 'By accessing and using Dbs, you agree to be bound by these Terms of Service. If you do not accept these terms, please do not use our service.',
    'terms.section1': '1. Acceptance of Terms',
    'terms.section2': '2. Service Description',
    'terms.section3': '3. Registration Terms',
    'terms.section4': '4. Acceptable Use',
    'terms.section5': '5. Prohibited Uses',
    'terms.section6': '6. Intellectual Property',
    'terms.section7': '7. Limitation of Liability',
    'terms.section8': '8. Subscriptions and Payments',
    'terms.section9': '9. Suspension and Termination',
    'terms.section10': '10. Modifications of Terms',
    'terms.section11': '11. Applicable Law',
    'terms.section12': '12. Contact',
    'terms.service.desc': 'Dbs is a cybersecurity platform offering OSINT (Open Source Intelligence) search services and dark web monitoring. Our services allow users to search publicly available information and data from known breaches.',
    'terms.registration': 'To use Dbs, you must:',
    'terms.reg1': 'Be at least 18 years old',
    'terms.reg2': 'Provide accurate information during registration',
    'terms.reg3': 'Maintain confidentiality of your credentials',
    'terms.reg4': 'Be responsible for all activities on your account',
    'terms.acceptable': 'You agree to use Dbs only for legal and ethical purposes, including:',
    'terms.acceptable1': 'Verify your own personal data',
    'terms.acceptable2': 'Authorized security research',
    'terms.acceptable3': 'Legitimate investigations in a professional context',
    'terms.acceptable4': 'Protection against cybersecurity threats',
    'terms.prohibited': 'It is strictly prohibited to use Dbs for:',
    'terms.prohibited1': 'Harassment, stalking or intimidation of individuals',
    'terms.prohibited2': 'Fraudulent or illegal activities',
    'terms.prohibited3': 'Data collection for spam or unsolicited marketing',
    'terms.prohibited4': 'Attempting to harm individuals or organizations',
    'terms.prohibited5': 'Resale or redistribution of obtained data',
    'terms.prohibited6': 'Abusive automation or mass scraping',
    'terms.prohibited7': 'Circumventing your subscription limits',
    'terms.ip.text': 'All content, logos, designs and features of Dbs are protected by intellectual property rights. You may not copy, modify, distribute or commercially exploit our platform without written permission.',
    'terms.liability': 'Dbs is provided "as is". We do not warrant:',
    'terms.liability1': 'The accuracy or completeness of search results',
    'terms.liability2': 'Continuous availability of the service',
    'terms.liability3': 'The absence of bugs or errors',
    'terms.liability.desc': 'Dbs shall not be liable for any direct or indirect damages resulting from use of the platform.',
    'terms.subscription': 'Subscriptions are billed monthly or annually according to your choice. Payments are non-refundable, except as required by law. You may cancel your subscription at any time.',
    'terms.suspension': 'We reserve the right to suspend or terminate your account in case of:',
    'terms.suspension1': 'Violation of these Terms of Service',
    'terms.suspension2': 'Abusive or illegal use of the platform',
    'terms.suspension3': 'Non-payment of subscription fees',
    'terms.suspension4': 'Request from competent authorities',
    'terms.modifications': 'We may modify these terms at any time. Significant changes will be notified by email. Your continued use of the service after modification constitutes your acceptance of the new terms.',
    'terms.law': 'These terms are governed by French law. Any dispute will be subject to the jurisdiction of the courts of Paris, France.',
    'terms.contact': 'For any questions about these terms:',
    'terms.contact.email': 'Email: legal@Dbs.io',
    'terms.contact.address': 'Address: 123 Rue de la Sécurité, 75001 Paris, France',
    'terms.confirmation': 'By using Dbs, you confirm that you have read, understood and accepted these Terms of Service.',
    'security.title': 'Security & Trust',
    'security.badge': 'Legal',
    'security.updated': 'Last updated: January 1, 2026',
    'security.section1': '1. Security Commitment',
    'security.section1.desc': 'Security is at the heart of Dbs. We apply recognized practices to protect the confidentiality, integrity and availability of information processed by the platform.',
    'security.section2': '2. Data Protection',
    'security.section2.desc': 'Data is encrypted in transit and at rest. By default, Dbs does not retain your search history to limit exposure of sensitive information.',
    'security.section3': '3. Access Controls',
    'security.section3.point1': 'Strengthened authentication and MFA options.',
    'security.section3.point2': 'Principle of least privilege for internal access.',
    'security.section3.point3': 'Periodic access reviews.',
    'security.section4': '4. Infrastructure and Monitoring',
    'security.section4.desc': 'Our infrastructure is hardened and continuously monitored. We apply regular updates, service segmentation and alerts for unusual activity.',
    'security.section5': '5. Secure Development',
    'security.section5.desc': 'Code is reviewed and tested before each deployment. We track dependencies, apply patches and reduce security regression risks.',
    'security.section6': '6. Incident Management',
    'security.section6.desc': 'In case of incident, we apply a documented response process, with analysis, remediation and appropriate communication if necessary.',
    'security.section7': '7. Responsible Disclosure',
    'security.section7.desc': 'You can report a vulnerability to security@Dbs.io. We analyze each report in good faith and communicate on resolution.',
    'security.section8': '8. User Best Practices',
    'security.section8.point1': 'Use a unique and strong password.',
    'security.section8.point2': 'Enable MFA as soon as possible.',
    'security.section8.point3': 'Do not share your credentials.',
    'security.section8.point4': 'Regularly check your account activity.',
    'security.section9': '9. Learn More',
    'security.section9.desc': 'For details on personal data processing, see the Privacy Policy.',
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window !== 'undefined') {
      return (localStorage.getItem('Dbs-language') as Language) || 'fr';
    }
    return 'fr';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
     
      localStorage.setItem('Dbs-language', lang);
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};








